name: Vite Deploy on Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and build
        run: |
          yarn install
          # pass --base if CNAME is not used
          # npm run build -- --base=/${{ github.event.repository.name }}/
          yarn build.demo
          
          # Enable Vue Router history mode with 404.html hack for Github Pages
          cd dist
          ln -s index.html 404.html

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: dist
